#+TITLE: TCA6408
#+AUTHOR: Peter Polidoro
#+EMAIL: peter@polidoro.io

* Library Information
- Name :: TCA6408
- Version :: 1.0.0
- License :: BSD
- URL :: https://github.com/janelia-arduino/TCA6408
- Author :: Peter Polidoro
- Email :: peter@polidoro.io

** Description

Arduino interface library for the TI TCA6408 8-bit I2C I/O Expander.

* Host Computer Setup

** Download this repository

[[https://github.com/janelia-arduino/TCA6408.git]]

#+BEGIN_SRC sh
git clone https://github.com/janelia-arduino/TCA6408.git
#+END_SRC

** PlatformIO

*** Install PlatformIO Core

[[https://docs.platformio.org/en/latest/core/installation/index.html]]

#+BEGIN_SRC sh
python3 -m venv .venv
source .venv/bin/activate
pip install platformio
pio --version
#+END_SRC

*** 99-platformio-udev.rules

Linux users have to install udev rules for PlatformIO supported boards/devices.

**** Download udev rules file to /etc/udev/rules.d

#+BEGIN_SRC sh
curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules
#+END_SRC

**** Restart udev management tool

#+BEGIN_SRC sh
sudo service udev restart
#+END_SRC

**** Add user to groups

#+BEGIN_SRC sh
sudo usermod -a -G dialout $USER && sudo usermod -a -G plugdev $USER
#+END_SRC

**** Remove modemmanager

#+BEGIN_SRC sh
sudo apt-get purge --auto-remove modemmanager
#+END_SRC

**** After setting up rules and groups

You will need to log out and log back in again (or reboot) for the user group changes to take effect.

After this file is installed, physically unplug and reconnect your board.

*** Compile the firmware

**** Gnu/Linux

#+BEGIN_SRC sh
make teensy-firmware
make mega-firmware
make uno-firmware
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio run -e teensy40
pio run -e mega
pio run -e uno
#+END_SRC

*** Upload the firmware

**** Gnu/Linux

#+BEGIN_SRC sh
make teensy-upload
make mega-upload
make uno-upload
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio run -e teensy40 -t upload
pio run -e mega -t upload
pio run -e uno -t upload
#+END_SRC

*** Serial Terminal Monitor

**** Gnu/Linux

#+BEGIN_SRC sh
make monitor
#+END_SRC

**** Other

#+BEGIN_SRC sh
pio device monitor
#+END_SRC



