name=lychee_library
version=1.0.1
author=ghutchins
maintainer=ghutchins
sentence=Lychee Library for ESP32.
paragraph=to build sPOD, switch and touchscreen programs
category=Communication
url=https://github.com/ghutchins/lychee_library
architectures=esp32
